version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
